### ISSUE TITLE
SecureShellServiceProvider not found

### ISSUE THREAD

**Issue by VijeshDatt** [faustbrian/laravel-ssh#3]
**Expected Behavior**
Package installs without issues.

**Current Behavior**
Initial installation happens without issues, however the publish part fails giving the following error:
In ProviderRepository.php line 208:
  Class 'KodeKeep\SecureShell\SecureShellServiceProvider' not found

**Possible Solution**

**Steps to Reproduce (for bugs)**
composer require kodekeep/laravel-ssh

**Context**
Cannot use the package at all since the composer.json get's reverted after failing.

**Your Environment**

- Version used: 1.0
- Environment name and version (e.g. node.js v10.15.3): 12.14.0
- Server type and version: -
- Operating System and version: Windows 10 v1909
- Link to your project:

**Comment by faustbrian** [comment]
https://github.com/faustbrian/laravel-ssh/releases/tag/1.0.1

**Comment by VijeshDatt** [comment]
Thanks so much man! Life saver!
